### ISSUE TITLE
Sorting a ticket list: be able to sort the ticket list based on PRIORITY LEVEL of the tickets

### ISSUE THREAD

**Issue by Cheeyau** [rster2002/cs-NoSQL-Project#29]

**Comment by Cheeyau** [comment]
fixed sort items by column header in listview

**Comment by rster2002** [comment]
Already merged. I'm not sure whether or not ListViewColumnSorter should be included in the View project or the Service project. Care to weigh in?

**Comment by Cheeyau** [comment]
oh lol, was de hele tijd in het engels te denken. In dit geval denk ik dat in view project hoort vanwege is het gebruik alleen in de view wordt gedaan.

**Comment by rster2002** [comment]
Okay 👍
